name: Publish package

on:
  release:
    types: [published] # run when a new release is published
    
env:
  name: ${{github.event.repository.name}} # Edit this if the package name differs from the repo name

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get clean version
        run: |
          echo cleanVersion=$(echo ${{github.ref_name}} | sed s/v//g) >> $GITHUB_ENV
      - name: Check that version matches
        run: |
          if [[ "$(grep -Po "\d+\.\d+\.\d+" $(find ./mods/Moblin.Archon -name mod.json))" != "${{ env.cleanVersion }}" ]]; then
            echo "::debug::${{env.cleanVersion}}"
            echo "::debug::$(cat $(find ./mods/Moblin.Archon -name mod.json ))"
            echo "::error::Version in mod.json does not match tag version"
            exit 1
          fi
  publish:
    runs-on: ubuntu-latest
    needs: verify
    permissions:
      contents: write
    steps:
      - name: Checkout ${{ matrix.branch }}
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - name: Create Folders
        run: |
          mkdir -p Moblin.Archon && cp -R mods/ icon.png LICENSE manifest.json README.md CHANGELOG.md Moblin.Archon/

      - name: Get clean version
        run: |
          echo cleanVersion=$(echo ${{github.ref_name}} | sed s/v//g) >> $GITHUB_ENV

      - uses: vimtor/action-zip@v1
        name: zip archon
        with:
          files: ./Moblin.Archon
          dest: ./Moblin.Archon_v${{ env.cleanVersion }}.zip
            
      - name: Attach the mod to the release
        uses: softprops/action-gh-release@v1
        with:
          files: ./Moblin.Archon_v${{ env.cleanVersion }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Thunderstore Package
        uses: GreenTF/upload-thunderstore-package@v3.1
        with:
          community: northstar
          # Name of the team to publish the mod under
          # This should be modified if your github username is different than your team name on Thunderstore
          namespace: "GalacticMoblin" # <------ DOUBLE CHECK THIS
          # Name of the package
          name: MoblinArchon # This can be modified if the package name differs from the repo name
          # Package version to publish
          version: ${{ github.ref_name }} # This is the tag that was created in the release
          # Description of the mod
          description: Implements the custom Archon Titan based off of cut content. # <----------- UPDATE THIS
          # Thunderstore API token
          token: ${{ secrets.TS_KEY }} 
          # Directory to wrap the contents of the repo in
          file: ./Moblin.Archon_v${{ env.cleanVersion }}.zip
          deps: northstar-Northstar-1.30.1 The_Peepeepoopoo_man-Titanframework-2.4.3 # <------------- Uncomment this line to add dependencies to your mod, each sparated by a space
          categories: Mods Server-side Client-side # <----------------------------- Add more categories as needed, separated by spaces
